INSERT INTO Areacodes (AreaCode, AreaName) VALUES (1, 'Central');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (3, 'Southwest');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (9, 'Van Nuys');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (6, 'Hollywood');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (18, 'Southeast');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (13, 'Newton');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (19, 'Mission');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (2, 'Rampart');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (4, 'Hollenbeck');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (10, 'West Valley');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (7, 'Wilshire');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (8, 'West LA');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (20, 'Olympic');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (21, 'Topanga');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (11, 'Northeast');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (12, '77th Street');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (14, 'Pacific');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (15, 'N Hollywood');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (5, 'Harbor');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (16, 'Foothill');
INSERT INTO Areacodes (AreaCode, AreaName) VALUES (17, 'Devonshire');
