INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (101, 'STREET');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (128, 'BUS STOP/LAYOVER (ALSO QUERY 124)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (502, 'MULTI-UNIT DWELLING');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (405, 'CLOTHING STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (102, 'SIDEWALK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (501, 'SINGLE FAMILY DWELLING');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (248, 'CELL PHONE STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (750, 'CYBERSPACE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (751, 'WEBSITE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (203, 'OTHER BUSINESS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (108, 'PARKING LOT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (504, 'OTHER RESIDENCE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (605, 'AUTOMATED TELLER MACHINE (ATM)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (404, 'DEPARTMENT STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (221, 'PUBLIC STORAGE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (707, 'GARAGE/CARPORT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (209, 'EQUIPMENT RENTAL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (702, 'OFFICE BUILDING/OFFICE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (726, 'POLICE FACILITY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (801, 'MTA BUS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (729, 'SPECIALTY SCHOOL/OTHER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (725, 'GOVERNMENT FACILITY (FEDERAL,STATE, COUNTY & CITY)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (737, 'SKATING RINK*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (124, 'BUS STOP');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (720, 'JUNIOR HIGH SCHOOL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (116, 'OTHER/OUTSIDE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (103, 'ALLEY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (122, 'VEHICLE, PASSENGER/TRUCK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (602, 'BANK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (506, 'ABANDONED BUILDING ABANDONED HOUSE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (212, 'TRANSPORTATION FACILITY (AIRPORT)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (505, 'MOTEL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (701, 'HOSPITAL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (112, 'BUS, SCHOOL, CHURCH');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (710, 'OTHER PREMISE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (120, 'STORAGE SHED');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (406, 'OTHER STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (721, 'HIGH SCHOOL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (145, 'MAIL BOX');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (503, 'HOTEL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (735, 'NIGHT CLUB (OPEN EVENINGS ONLY)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (604, 'FINANCE COMPANY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (109, 'PARK/PLAYGROUND');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (717, 'HEALTH SPA/GYM');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (708, 'CHURCH/CHAPEL (CHANGED 03-03 FROM CHURCH/TEMPLE)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (712, 'COLISEUM');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (104, 'DRIVEWAY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (152, 'UNDERPASS/BRIDGE*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (607, 'BANKING INSIDE MARKET-STORE *');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (234, 'OPTICAL OFFICE INSIDE STORE OR SUPERMARKET*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (238, 'TELECOMMUNICATION FACILITY/LOCATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (222, 'LAUNDROMAT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (119, 'PORCH, RESIDENTIAL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (507, 'CONDOMINIUM/TOWNHOUSE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (514, 'GROUP HOME');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (125, 'PAY PHONE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (220, 'NAIL SALON');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (154, 'TRAIN TRACKS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (704, 'ELEMENTARY SCHOOL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (740, 'OTHER PLACE OF WORSHIP');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (243, 'DIY CENTER (LOWES,HOME DEPOT,OSH,CONTRACTORS WAREHOUSE)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (517, 'MISSIONS/SHELTERS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (802, 'MUNICIPAL BUS LINE INCLUDES LADOT/DASH');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (732, 'POST OFFICE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (943, 'MTA - EXPO LINE - JEFFERSON/USC');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (121, 'YARD (RESIDENTIAL/BUSINESS)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (111, 'BUS-CHARTER/PRIVATE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (804, 'GREYHOUND OR INTERSTATE BUS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (207, 'BAR/COCKTAIL/NIGHTCLUB');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (518, 'TRANSITIONAL HOUSING/HALFWAY HOUSE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (301, 'GAS STATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (403, 'DRUG STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (210, 'RESTAURANT/FAST FOOD');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (733, 'BAR/SPORTS BAR (OPEN DAY & NIGHT)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (510, 'NURSING/CONVALESCENT/RETIREMENT HOME');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (603, 'CREDIT UNION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (208, 'AUTO SALES LOT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (123, 'PARKING UNDERGROUND/BUILDING');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (135, 'MTA PROPERTY OR PARKING LOT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (410, 'MEMBERSHIP STORE (COSTCO,SAMS CLUB)*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (247, 'CAR WASH');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (217, 'AUTO REPAIR SHOP');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (719, 'MEDICAL/DENTAL OFFICES');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (412, 'ELECTRONICS STORE (IE:RADIO SHACK, ETC.)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (834, 'LA UNION STATION (NOT LINE SPECIFIC)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (401, 'MINI-MART');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (402, 'MARKET');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (727, 'SHOPPING MALL (COMMON AREA)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (714, 'DODGER STADIUM');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (511, 'PROJECT/TENEMENT/PUBLIC HOUSING');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (723, 'PRIVATE SCHOOL/PRESCHOOL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (913, 'MTA - RED LINE - NORTH HOLLYWOOD');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (255, 'AUTO DEALERSHIP (CHEVY, FORD, BMW, MERCEDES, ETC.)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (408, 'AUTO SUPPLY STORE*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (252, 'COFFEE SHOP (STARBUCKS, COFFEE BEAN, PEETS, ETC.)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (741, 'STAPLES CENTER *');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (743, 'MASS GATHERING LOCATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (706, 'SEX ORIENTED/BOOK STORE/STRIP CLUB/GENTLEMANS CLUB');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (202, 'LIQUOR STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (407, 'HARDWARE/BUILDING SUPPLY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (905, 'MTA - RED LINE - WILSHIRE/VERMONT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (516, 'SINGLE RESIDENCE OCCUPANCY (SROS) LOCATIONS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (230, 'DAY CARE/ADULTS*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (742, 'SPORTS VENUE, OTHER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (718, 'MASSAGE PARLOR');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (213, 'WAREHOUSE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (709, 'PUBLIC RESTROOM(INDOORS-INSIDE)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (118, 'CONSTRUCTION SITE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (932, 'MTA - BLUE LINE - PICO');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (146, 'PATIO*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (957, 'MTA - GREEN LINE - HARBOR FWY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (149, 'RIVER BED*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (117, 'BEACH');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (249, 'NURSERY/FLOWER SHOP');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (935, 'MTA - BLUE LINE - WASHINGTON');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (242, 'DISCOUNT STORE (99 CENT,DOLLAR,ETC.');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (509, 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RVS/MOTORHOME');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (204, 'MANUFACTURING COMPANY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (211, 'PAWN SHOP');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (903, 'MTA - RED LINE - 7TH AND METRO CENTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (415, 'THE GROVE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (218, 'BEAUTY/BARBER SHOP');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (158, 'TRANSIENT ENCAMPMENT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (231, 'DAY CARE/CHILDREN*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (738, 'LIBRARY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (416, 'THE BEVERLY CENTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (515, 'APARTMENT/CONDO COMMON LAUNDRY ROOM');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (201, 'JEWELRY STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (880, 'MTA - ORANGE LINE - CANOGA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (508, 'FRAT HOUSE/SORORITY/DORMITORY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (417, 'THE BEVERLY CONNECTION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (107, 'VACANT LOT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (971, 'MTA - GOLD LINE - HIGHLAND PARK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (114, 'TAXI');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (232, 'DELIVERY SERVICE (FED EX, UPS, COURIERS,COURIER SERVICE)*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (151, 'TOW YARD*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (225, 'RECORD-CD MUSIC/COMPUTER GAME STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (722, 'COLLEGE/JUNIOR COLLEGE/UNIVERSITY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (711, 'ARCADE,GAME ROOM/VIDEO GAMES (EXAMPLE CHUCKIE CHEESE)*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (251, 'RECYCLING CENTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (713, 'CONVENTION CENTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (936, 'MTA - BLUE LINE - VERNON');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (907, 'MTA - RED LINE - VERMONT/SANTA MONICA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (752, 'FIRE STATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (413, 'FURNITURE STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (900, 'MTA - RED LINE - UNION STATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (911, 'MTA - RED LINE - HOLLYWOOD/HIGHLAND');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (811, 'OTHER RR TRAIN (UNION PAC, SANTE FE ETC');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (753, 'DETENTION/JAIL FACILITY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (946, 'MTA - EXPO LINE - EXPO/WESTERN');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (409, 'BEAUTY SUPPLY STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (882, 'MTA - ORANGE LINE - SHERMAN WAY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (140, 'BALCONY*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (906, 'MTA - RED LINE - VERMONT/BEVERLY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (908, 'MTA - RED LINE - VERMONT/SUNSET');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (902, 'MTA - RED LINE - PERSHING SQUARE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (942, 'MTA - EXPO LINE - LATTC/ORTHO INSTITUTE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (950, 'MTA - EXPO LINE - LA CIENEGA/JEFFERSON');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (254, 'STUDIO (FILM/PHOTOGRAPHIC/MUSIC)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (144, 'GOLF COURSE*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (901, 'MTA - RED LINE - CIVIC CENTER/GRAND PARK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (730, 'SYNAGOGUE/TEMPLE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (728, 'ELEVATOR');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (954, 'MTA - EXPO LINE - EXPO/BUNDY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (744, 'HIGH-RISE BUILDING');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (904, 'MTA - RED LINE - WESTLAKE/MACARTHUR PARK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (235, 'PHARMACY INSIDE STORE OR SUPERMARKET*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (891, 'MTA - SILVER LINE - DOWNTOWN STREET STOPS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (868, 'MTA - ORANGE LINE - NORTH HOLLYWOOD');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (150, 'TOOL SHED*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (922, 'MTA - PURPLE LINE - WILSHIRE/WESTERN');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (205, 'GUN/SPORTING GOODS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (910, 'MTA - RED LINE - HOLLYWOOD/VINE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (236, 'VISION CARE FACILITY*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (141, 'CEMETARY*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (148, 'PUBLIC RESTROOM/OUTSIDE*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (110, 'FREEWAY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (909, 'MTA - RED LINE - HOLLYWOOD/WESTERN');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (139, 'AMUSEMENT PARK*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (216, 'SWAP MEET');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (244, 'TOBACCO SHOP');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (934, 'MTA - BLUE LINE - SAN PEDRO');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (705, 'SLIPS/DOCK/MARINA/BOAT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (921, 'MTA - PURPLE LINE - WILSHIRE/NORMANDIE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (755, 'VETERINARIAN/ANIMAL HOSPITAL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (948, 'MTA - EXPO LINE - FARMDALE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (142, 'DRIVE THRU*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (945, 'MTA - EXPO LINE - EXPO/VERMONT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (933, 'MTA - BLUE LINE - GRAND/LATTC');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (919, 'MTA - PURPLE LINE - WESTLAKE/MACARTHUR PARK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (912, 'MTA - RED LINE - UNIVERSAL CITY/STUDIO CITY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (956, 'MTA - GREEN LINE - AVALON');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (245, 'CATERING/ICE CREAM TRUCK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (754, 'MUSEUM');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (969, 'MTA - GOLD LINE - HERITAGE SQ');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (106, 'TUNNEL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (810, 'AMTRAK TRAIN');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (302, 'FACTORY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (241, 'ENERGY PLANT/FACILITY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (931, 'MTA - BLUE LINE - 7TH AND METRO CENTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (157, 'VEHICLE STORAGE LOT (CARS, TRUCKS, RVS, BOATS, TRAILERS, ETC.)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (748, 'CULTURAL SIGNIFICANCE/MONUMENT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (878, 'MTA - ORANGE LINE - PIERCE COLLEGE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (115, 'AIRCRAFT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (156, 'VALET');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (303, 'OIL REFINERY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (736, 'SKATEBOARD FACILITY/SKATEBOARD PARK*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (601, 'SAVINGS & LOAN');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (250, 'COMPUTER SERVICES/REPAIRS/SALES');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (233, 'TATTOO PARLOR*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (745, 'WATER FACILITY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (513, 'ABATEMENT LOCATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (703, 'ENTERTAINMENT/COMEDY CLUB (OTHER)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (229, 'CHECK CASHING*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (138, 'STAIRWELL*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (147, 'POOL-PUBLIC/OUTDOOR OR INDOOR*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (411, 'PET STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (809, 'METROLINK TRAIN');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (835, '7TH AND METRO CENTER (NOT LINE SPECIFIC)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (206, 'TV/RADIO/APPLIANCE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (155, 'DAM/RESERVOIR');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (883, 'MTA - ORANGE LINE - ROSCOE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (963, 'MTA - GOLD LINE - MARIACHI PLAZA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (757, 'BASKETBALL COURTS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (739, 'SPORTS ARENA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (519, 'SHORT-TERM VACATION RENTAL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (228, 'BOWLING ALLEY*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (937, 'MTA - BLUE LINE - 103RD/WATTS TOWERS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (137, 'TRAM/STREETCAR(BOXLIKE WAG ON RAILS)*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (961, 'MTA - GOLD LINE - INDIANA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (920, 'MTA - PURPLE LINE - WILSHIRE/VERMONT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (947, 'MTA - EXPO LINE - EXPO/CRENSHAW');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (731, 'MOSQUE*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (127, 'TRASH CAN/TRASH DUMPSTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (873, 'MTA - ORANGE LINE - SEPULVEDA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (953, 'MTA - EXPO LINE - EXPO/SEPULVEDA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (716, 'THEATRE/MOVIE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (967, 'MTA - GOLD LINE - CHINATOWN');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (871, 'MTA - ORANGE LINE - WOODMAN');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (215, 'TRAIN DEPOT/TERMINAL, OTHER THAN MTA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (872, 'MTA - ORANGE LINE - VAN NUYS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (968, 'MTA - GOLD LINE - LINCOLN/CYPRESS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (214, 'BUS DEPOT/TERMINAL, OTHER THAN MTA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (239, 'MEDICAL MARIJUANA FACILITIES/BUSINESSES');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (219, 'CLEANER/LAUNDROMAT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (724, 'TRADE SCHOOL (MEDICAL-TECHNICAL-BUSINESS)*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (962, 'MTA - GOLD LINE - SOTO');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (970, 'MTA - GOLD LINE - SOUTHWEST MUSEUM');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (876, 'MTA - ORANGE LINE - RESEDA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (897, 'MTA - SILVER LINE - HARBOR GATEWAY TRANSIT CTR');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (253, 'MORTUARY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (129, 'TERMINAL, OTHER THAN MTA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (918, 'MTA - PURPLE LINE - 7TH AND METRO CENTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (414, 'BOOK STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (304, 'GARMENT MANUFACTURER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (803, 'RETIRED (DUPLICATE) DO NOT USE THIS CODE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (608, 'BANK DROP BOX/MONEY DROP-OUTSIDE OF BANK*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (895, 'MTA - SILVER LINE - HARBOR FWY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (892, 'MTA - SILVER LINE - 37TH ST/USC');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (305, 'CHEMICAL STORAGE/MANUFACTURING PLANT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (951, 'MTA - EXPO LINE - PALMS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (113, 'TRUCK, COMMERICAL');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (949, 'MTA - EXPO LINE - EXPO/LA BREA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (940, 'MTA - EXPO LINE - 7TH AND METRO CENTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (889, 'MTA - SILVER LINE - LAC/USC MEDICAL CENTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (136, 'OTHER INTERSTATE, CHARTER BUS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (944, 'MTA - EXPO LINE - EXPO PARK/USC');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (143, 'ESCALATOR*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (964, 'MTA - GOLD LINE - PICO/ALISO');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (237, 'HOSPICE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (966, 'MTA - GOLD LINE - UNION STATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (958, 'MTA - GREEN LINE - AVIATION/LAX');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (105, 'PEDESTRIAN OVERCROSSING');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (890, 'MTA - SILVER LINE - UNION STATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (227, 'ABORTION CLINIC/ABORTION FACILITY*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (512, 'FOSTER HOME BOYS OR GIRLS*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (877, 'MTA - ORANGE LINE - TAMPA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (240, 'DEPT OF DEFENSE FACILITY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (952, 'MTA - EXPO LINE - WESTWOOD/RANCHO PARK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (805, 'RETIRED (DUPLICATE) DO NOT USE THIS CODE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (606, 'DRIVE THRU BANKING (WINDOW)*');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (879, 'MTA - ORANGE LINE - DE SOTO');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (224, 'SURPLUS SURVIVAL STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (223, 'VIDEO RENTAL STORE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (746, 'SEWAGE FACILITY/PIPE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (246, 'METHADONE CLINIC');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (869, 'MTA - ORANGE LINE - LAUREL CANYON');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (884, 'MTA - ORANGE LINE - NORDHOFF');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (915, 'MTA - PURPLE LINE - UNION STATION');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (126, 'TRAIN, OTHER THAN MTA (ALSO QUERY 809/810/811)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (916, 'MTA - PURPLE LINE - CIVIC CENTER/GRAND PARK');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (893, 'MTA - SILVER LINE - SLAUSON');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (875, 'MTA - ORANGE LINE - BALBOA');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (917, 'MTA - PURPLE LINE - PERSHING SQUARE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (941, 'MTA - EXPO LINE - PICO');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (734, 'HOCKEY RINK/ICE HOCKEY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (874, 'MTA - ORANGE LINE - WOODLEY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (758, 'HANDBALL COURTS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (894, 'MTA - SILVER LINE - MANCHESTER');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (756, 'MUSCLE BEACH');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (885, 'MTA - ORANGE LINE - CHATSWORTH');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (836, 'HARBOR FRWY STATION (NOT LINE SPECIFIC)');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (965, 'MTA - GOLD LINE - LITTLE TOKYO/ARTS DISTRICT');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (898, 'MTA - SILVER LINE - PACIFIC COAST HWY');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (870, 'MTA - ORANGE LINE - VALLEY COLLEGE');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (896, 'MTA - SILVER LINE - ROSECRANS');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (418, 'nan');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (256, 'nan');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (974, 'nan');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (972, 'nan');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (973, 'nan');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (976, 'nan');
INSERT INTO Premiscodes (PremisCd, PremisName) VALUES (975, 'nan');
